service: alexaday2018
provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:AWS_REGION}
  memorySize: 256
  iamRoleStatements:
  - Effect: Allow
    Action:
    - polly:DescribeVoices
    - polly:SynthesizeSpeech
    - s3:PutObject
    Resource: "*"
plugins:
- serverless-webpack
- serverless-offline
custom:
  webpackIncludeModules: true
functions:
  skill:
    handler: handlers/skill.default
    events:
    - alexaSkill
    environment:
      BUCKET:
        Ref: Bucket
resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
          - Status: Enabled
            ExpirationInDays: 3
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: Bucket
        PolicyDocument:
          Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource:
              Fn::Join:
              - ""
              - - Fn::GetAtt:
                  - Bucket
                  - Arn
                - /*
            Principal: "*"
